# docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  fastapi:
    volumes:
      - .:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  arq:
    volumes:
      - .:/app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: onecrawler-ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: [ "http", "fastapi:8000" ]
    ports:
      - "4040:4040"
    depends_on:
      fastapi:
        condition: service_started
